# deploy-boilerplate/roles/postgres/tasks/main.yml
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: true

- name: Save PostgreSQL admin credentials
  copy:
    content: |
      POSTGRES_USER=admin
      POSTGRES_PASSWORD=admin
    dest: /var/secrets/pg_pw.txt
    owner: hng
    group: hng
    mode: '0600'

- name: Create PostgreSQL database and user
  become_user: postgres
  postgresql_db:
    name: myappdb
  postgresql_user:
    name: admin
    password: admin
    priv: "ALL"
