---
- hosts: ec2
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    # Common tasks
    - name: Create user hng with sudo privileges
      user:
        name: hng
        groups: sudo
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install acl package
      apt:
        name: acl
        state: present

    - name: Create /var/secrets directory
      file:
        path: /var/secrets
        state: directory
        owner: hng
        group: hng
        mode: '0750'

    - name: Create /var/log/stage_5b directory
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng
        mode: '0750'

    # PostgreSQL tasks
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

     - name: Install PostgreSQL contrib package
      apt:
        name: postgresql-contrib
        state: present

    - name: Start and enable PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Save PostgreSQL admin credentials
      copy:
        content: |
          POSTGRES_USER=admin
          POSTGRES_PASSWORD=secure_password
        dest: /var/secrets/pg_pw.txt
        owner: hng
        group: hng
        mode: '0600'

    - name: Create PostgreSQL database and user
      become_user: postgres
      postgresql_db:
        name: myappdb

    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: postgres
        password: secure_password
        priv: "ALL"

    # Redis tasks
    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Start and enable Redis service
      service:
        name: redis-server
        state: started
        enabled: true

    # Application tasks
    - name: Clone repository
      git:
        repo: 'https://github.com/hngprojects/hng_boilerplate_expressjs.git'
        dest: /opt/stage_5c
        version: devops
        force: yes

    - name: Change ownership of /opt/stage_5b
      file:
        path: /opt/stage_5c
        state: directory
        owner: hng
        group: hng
        recurse: yes

    - name: Add Yarn APT key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Add Yarn APT repository
      apt_repository:
        repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
        state: present

    - name: Install Yarn
      apt:
        name: yarn
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install application dependencies
      npm:
        path: /opt/stage_5c
        state: present

    - name: Configure environment variables
      copy:
        content: |
          PORT=3000
          DATABASE_URL=postgresql://admin:secure_password@localhost/myappdb
          REDIS_URL=redis://localhost:6379
        dest: /opt/stage_5c/.env
        owner: hng
        group: hng
        mode: '0600'

    - name: Start application
      shell: "npm start > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &"
      args:
        chdir: /opt/stage_5c
      environment:
        NODE_ENV: production

    # Nginx tasks
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Configure Nginx to reverse proxy
      copy:
        content: |
          server {
            listen 80;
            server_name localhost;

            location / {
              proxy_pass http://127.0.0.1:3000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
            }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Test Nginx configuration
      command: nginx -t

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

