# deploy-boilerplate/roles/redis/tasks/main.yml
- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Start and enable Redis service
  service:
    name: redis-server
    state: started
    enabled: true
