# deploy-boilerplate/roles/app/tasks/main.yml
- name: Clone repository
  git:
    repo: 'https://github.com/yourusername/yourrepo.git'
    dest: /opt/stage_5b
    version: devops
    force: yes

- name: Change ownership of /opt/stage_5b
  file:
    path: /opt/stage_5b
    state: directory
    owner: hng
    group: hng
    recurse: yes

- name: Install application dependencies
  command: npm install
  args:
    chdir: /opt/stage_5b

- name: Configure environment variables
  copy:
    content: |
      PORT=3000
      DATABASE_URL=postgresql://admin:secure_password@localhost/myappdb
      REDIS_URL=redis://localhost:6379
    dest: /opt/stage_5b/.env
    owner: hng
    group: hng
    mode: '0600'

- name: Start application
  shell: "npm start > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &"
  args:
    chdir: /opt/stage_5b
  environment:
    NODE_ENV: production
